In [1]:
import pandas as pd
import torch
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [3]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


In [4]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [17]:
df.shape

(569, 31)

In [18]:
df.iloc[:,1:]

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


In [19]:
df.iloc[:, 0]

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [20]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [21]:
x_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
45,18.650,17.60,123.70,1076.0,0.10990,0.16860,0.19740,0.10090,0.1907,0.06049,...,22.82,21.32,150.60,1567.0,0.16790,0.50900,0.73450,0.23780,0.3799,0.09185
443,10.570,18.32,66.82,340.9,0.08142,0.04462,0.01993,0.01111,0.2372,0.05768,...,10.94,23.31,69.35,366.3,0.09794,0.06542,0.03986,0.02222,0.2699,0.06736
127,19.000,18.91,123.40,1138.0,0.08217,0.08028,0.09271,0.05627,0.1946,0.05044,...,22.32,25.73,148.20,1538.0,0.10210,0.22640,0.32070,0.12180,0.2841,0.06541
234,9.567,15.91,60.21,279.6,0.08464,0.04087,0.01652,0.01667,0.1551,0.06403,...,10.51,19.16,65.74,335.9,0.15040,0.09515,0.07161,0.07222,0.2757,0.08178
218,19.800,21.56,129.70,1230.0,0.09383,0.13060,0.12720,0.08691,0.2094,0.05581,...,25.73,28.64,170.30,2009.0,0.13530,0.32350,0.36170,0.18200,0.3070,0.08255
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,17.140,16.40,116.00,912.7,0.11860,0.22760,0.22290,0.14010,0.3040,0.07413,...,22.25,21.40,152.40,1461.0,0.15450,0.39490,0.38530,0.25500,0.4066,0.10590
474,10.880,15.62,70.41,358.9,0.10070,0.10690,0.05115,0.01571,0.1861,0.06837,...,11.94,19.35,80.78,433.1,0.13320,0.38980,0.33650,0.07966,0.2581,0.10800
354,11.140,14.07,71.24,384.6,0.07274,0.06064,0.04505,0.01471,0.1690,0.06083,...,12.12,15.82,79.62,453.5,0.08864,0.12560,0.12010,0.03922,0.2576,0.07018
429,12.720,17.67,80.98,501.3,0.07896,0.04522,0.01402,0.01835,0.1459,0.05544,...,13.82,20.96,88.87,586.8,0.10680,0.09605,0.03469,0.03612,0.2165,0.06025


In [22]:
x_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
478,11.49,14.59,73.99,404.9,0.10460,0.08228,0.05308,0.01969,0.1779,0.06574,...,12.40,21.90,82.04,467.6,0.1352,0.20100,0.2596,0.07431,0.2941,0.09180
373,20.64,17.35,134.80,1335.0,0.09446,0.10760,0.15270,0.08941,0.1571,0.05478,...,25.37,23.17,166.80,1946.0,0.1562,0.30550,0.4159,0.21120,0.2689,0.07055
143,12.90,15.92,83.74,512.2,0.08677,0.09509,0.04894,0.03088,0.1778,0.06235,...,14.48,21.82,97.17,643.8,0.1312,0.25480,0.2090,0.10120,0.3549,0.08118
134,18.45,21.91,120.20,1075.0,0.09430,0.09709,0.11530,0.06847,0.1692,0.05727,...,22.52,31.39,145.60,1590.0,0.1465,0.22750,0.3965,0.13790,0.3109,0.07610
370,16.35,23.29,109.00,840.4,0.09742,0.14970,0.18110,0.08773,0.2175,0.06218,...,19.38,31.03,129.30,1165.0,0.1415,0.46650,0.7087,0.22480,0.4824,0.09614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,21.75,20.99,147.30,1491.0,0.09401,0.19610,0.21950,0.10880,0.1721,0.06194,...,28.19,28.18,195.90,2384.0,0.1272,0.47250,0.5807,0.18410,0.2833,0.08858
174,10.66,15.15,67.49,349.6,0.08792,0.04302,0.00000,0.00000,0.1928,0.05975,...,11.54,19.20,73.20,408.3,0.1076,0.06791,0.0000,0.00000,0.2710,0.06164
49,13.49,22.30,86.91,561.0,0.08752,0.07698,0.04751,0.03384,0.1809,0.05718,...,15.15,31.82,99.00,698.8,0.1162,0.17110,0.2282,0.12820,0.2871,0.06917
344,11.71,15.45,75.03,420.3,0.11500,0.07281,0.04006,0.03250,0.2009,0.06506,...,13.06,18.16,84.16,516.4,0.1460,0.11150,0.1087,0.07864,0.2765,0.07806


Scaling

In [23]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [24]:
x_train_scaled

array([[ 1.27749697, -0.39136196,  1.29849677, ...,  1.87068794,
         1.41449211,  0.40651322],
       [-0.99363292, -0.22291702, -1.01954276, ..., -1.3937649 ,
        -0.33168676, -0.90422193],
       [ 1.37587512, -0.08488576,  1.28627082, ...,  0.11414035,
        -0.10627095, -1.00858835],
       ...,
       [-0.83341707, -1.21721004, -0.83941381, ..., -1.13633983,
        -0.52694131, -0.75329204],
       [-0.38930999, -0.37498537, -0.44247806, ..., -1.18328205,
        -1.17937724, -1.28475794],
       [-0.75190374, -0.45920783, -0.74079117, ..., -0.76080206,
        -0.51424183, -0.17633308]], shape=(455, 30))

In [25]:
x_test_scaled

array([[-7.35038919e-01, -1.09555537e+00, -7.27342626e-01, ...,
        -6.04984179e-01,  5.24725879e-02,  4.03837160e-01],
       [ 1.83684703e+00, -4.49849783e-01,  1.75085680e+00, ...,
         1.46789341e+00, -3.47561118e-01, -7.33489177e-01],
       [-3.38715511e-01, -7.84400139e-01, -3.29999354e-01, ...,
        -1.97798275e-01,  1.01763327e+00, -1.64558402e-01],
       ...,
       [-1.72878056e-01,  7.08209142e-01, -2.00811849e-01, ...,
         2.11053320e-01, -5.86478858e-02, -8.07348488e-01],
       [-6.73201224e-01, -8.94357249e-01, -6.84959344e-01, ...,
        -5.39416497e-01, -2.26916032e-01, -3.31544669e-01],
       [ 2.52549409e+00,  1.30349436e-01,  2.45588640e+00, ...,
         1.69806172e+00,  8.72217219e-05, -6.14672026e-01]],
      shape=(114, 30))

In [26]:
y_train

45     M
443    B
127    M
234    B
218    M
      ..
25     M
474    B
354    B
429    B
142    B
Name: diagnosis, Length: 455, dtype: object

In [27]:
y_test

478    B
373    M
143    B
134    M
370    M
      ..
272    M
174    B
49     B
344    B
503    M
Name: diagnosis, Length: 114, dtype: object

Encoding

In [28]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

In [29]:
y_train_encoded

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,

In [30]:
y_test_encoded

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1])

In [31]:
x_train_scaled
x_test_scaled
y_train_encoded
y_test_encoded
print("")

In [32]:
x_train_tensor = torch.from_numpy(x_train_scaled)
x_test_tensor = torch.from_numpy(x_test_scaled)
y_train_tensor = torch.from_numpy(y_train_encoded).to(torch.float64)
y_test_tensor = torch.from_numpy(y_test_encoded).to(torch.float64)

In [33]:
x_train_tensor.shape[1]

30

In [34]:
y_train.shape

(455,)

This means that there will be 30 input going to the network and 1 output comming out of there (M or B)

In [35]:
# at the rate which the model steps move
learning_rate = 0.1
# number of times we send the whole dataset to the ANN
epochs = 22

In [ ]:
# defining the model
class ANN():
    def __init__(self, X):
        self.weight = torch.rand((X.shape[1], 1), dtype= torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype= torch.float64, requires_grad= True)
    
    def forward_pass(self, X):
        z = X @ self.weight + self.bias
        self.y_pred = torch.sigmoid(z).reshape(X.shape[0])
        return self.y_pred
    
    def loss_function(self, y_real):
        loss_fn = torch.nn.BCELoss()
        self.loss = loss_fn(self.y_pred, y_real)
        return self.loss.item()
    
    def backward_propagation(self, learning_rate):
        self.loss.backward()
        gradient = self.weight.grad
        with torch.no_grad():
            self.weight -=learning_rate * gradient
        self.weight.grad.zero_()
        return self.weight

In [38]:
model = ANN(x_train_tensor)

1. Forward Propagation
2. Loss Calculation
3. Backward Propagtation
4. Adjustment

In [39]:
import time
for epoch in range(epochs):
    y_prep = model.forward_pass(x_train_tensor)
    loss = model.loss_function(y_train_tensor)
    print("epoch: ", epoch, "====> loss", loss)
    new_weight = model.backward_propagation(learning_rate)

epoch:  0 ====> loss 0.377910590395329
epoch:  1 ====> loss 0.3650321852255322
epoch:  2 ====> loss 0.35254967674002663
epoch:  3 ====> loss 0.3404616523138999
epoch:  4 ====> loss 0.3287680751881191
epoch:  5 ====> loss 0.31747000047896456
epoch:  6 ====> loss 0.30656913406251707
epoch:  7 ====> loss 0.2960672419865759
epoch:  8 ====> loss 0.28596546313482707
epoch:  9 ====> loss 0.27626362072943267
epoch:  10 ====> loss 0.2669596522670538
epoch:  11 ====> loss 0.2580492604163704
epoch:  12 ====> loss 0.2495258331322019
epoch:  13 ====> loss 0.2413806121693739
epoch:  14 ====> loss 0.23360303612163144
epoch:  15 ====> loss 0.22618116541488287
epoch:  16 ====> loss 0.2191021096296675
epoch:  17 ====> loss 0.21235240646088221
epoch:  18 ====> loss 0.20591833048088679
epoch:  19 ====> loss 0.19978613022115657
epoch:  20 ====> loss 0.19394220276359297
epoch:  21 ====> loss 0.18837321859970926


In [40]:
# testing the ANN
y_pred = model.forward_pass(x_test_tensor)
loss = model.loss_function(y_test_tensor)
print(loss)

0.13208426567189496


In [41]:
y_pred

tensor([3.9345e-03, 9.9956e-01, 2.0016e-02, 9.9777e-01, 9.9985e-01, 9.8497e-01,
        9.9967e-01, 1.4797e-04, 9.9657e-01, 5.4718e-02, 3.5051e-01, 9.6679e-01,
        5.1118e-01, 1.6287e-03, 1.5344e-01, 6.5362e-04, 1.0000e+00, 2.7373e-03,
        9.9999e-01, 2.0442e-02, 1.0389e-02, 8.5961e-02, 9.0482e-02, 9.4318e-05,
        2.6027e-02, 1.0557e-01, 9.7266e-01, 1.0000e+00, 1.7061e-02, 3.9079e-04,
        8.5344e-04, 2.9553e-03, 7.5362e-04, 9.9272e-01, 7.2403e-04, 2.0843e-02,
        3.8979e-01, 9.8484e-03, 2.5748e-01, 5.3885e-02, 1.0000e+00, 8.6940e-02,
        2.0306e-03, 9.9428e-01, 9.9988e-01, 2.6394e-03, 9.3632e-01, 1.0000e+00,
        2.5113e-01, 6.0439e-02, 9.3711e-01, 1.7577e-03, 9.7343e-01, 3.4536e-02,
        9.7337e-01, 9.9945e-01, 1.6340e-03, 6.2775e-01, 7.5892e-02, 9.9819e-01,
        2.1566e-03, 5.4437e-01, 1.0121e-01, 6.4156e-03, 3.5890e-02, 4.2155e-04,
        9.9906e-01, 1.1215e-02, 6.3857e-01, 8.9835e-03, 7.4821e-01, 4.9592e-02,
        6.3061e-03, 9.4165e-01, 7.9303e-

In [42]:
y_test_tensor

tensor([0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0.,
        1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
        1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0.,
        1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
        0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
        1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1.,
        0., 1., 0., 0., 0., 1.], dtype=torch.float64)

In [43]:
y_train_tensor

tensor([1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0.,
        0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
        1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0.,
        1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0.,
        1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1.,
        0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1.,
        1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0.,
        0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
        1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
        1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
        1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1.,
        0., 0., 0., 1., 1., 0., 1., 1., 