In [202]:
import pandas as pd
import torch
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [203]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [204]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


In [205]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [206]:
df.shape

(569, 31)

In [207]:
df.iloc[:,1:]

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


In [208]:
df.iloc[:, 0]

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [209]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [210]:
x_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
388,11.27,15.50,73.38,392.0,0.08365,0.11140,0.10070,0.027570,0.1810,0.07252,...,12.04,18.93,79.73,450.0,0.1102,0.28090,0.30210,0.08272,0.2157,0.10430
91,15.37,22.76,100.20,728.2,0.09200,0.10360,0.11220,0.074830,0.1717,0.06097,...,16.43,25.84,107.50,830.9,0.1257,0.19970,0.28460,0.14760,0.2556,0.06828
425,10.03,21.28,63.19,307.3,0.08117,0.03912,0.00247,0.005159,0.1630,0.06439,...,11.11,28.94,69.92,376.3,0.1126,0.07094,0.01235,0.02579,0.2349,0.08061
205,15.12,16.68,98.78,716.6,0.08876,0.09588,0.07550,0.040790,0.1594,0.05986,...,17.77,20.24,117.70,989.5,0.1491,0.33310,0.33270,0.12520,0.3415,0.09740
371,15.19,13.21,97.65,711.8,0.07963,0.06934,0.03393,0.026570,0.1721,0.05544,...,16.20,15.73,104.50,819.1,0.1126,0.17370,0.13620,0.08178,0.2487,0.06766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,11.41,14.92,73.53,402.0,0.09059,0.08155,0.06181,0.023610,0.1167,0.06217,...,12.37,17.70,79.12,467.2,0.1121,0.16100,0.16480,0.06296,0.1811,0.07427
427,10.80,21.98,68.79,359.9,0.08801,0.05743,0.03614,0.014040,0.2016,0.05977,...,12.76,32.04,83.69,489.5,0.1303,0.16960,0.19270,0.07485,0.2965,0.07662
423,13.66,19.13,89.46,575.3,0.09057,0.11470,0.09657,0.048120,0.1848,0.06181,...,15.14,25.50,101.40,708.8,0.1147,0.31670,0.36600,0.14070,0.2744,0.08839
12,19.17,24.80,132.40,1123.0,0.09740,0.24580,0.20650,0.111800,0.2397,0.07800,...,20.96,29.94,151.70,1332.0,0.1037,0.39030,0.36390,0.17670,0.3176,0.10230


In [211]:
x_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
202,23.290,26.67,158.90,1685.0,0.11410,0.20840,0.352300,0.162000,0.2200,0.06229,...,25.120,32.68,177.00,1986.0,0.15360,0.41670,0.789200,0.27330,0.3198,0.08762
568,7.760,24.54,47.92,181.0,0.05263,0.04362,0.000000,0.000000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.000000,0.00000,0.2871,0.07039
318,9.042,18.90,60.07,244.5,0.09968,0.19720,0.197500,0.049080,0.2330,0.08743,...,10.060,23.40,68.62,297.1,0.12210,0.37480,0.460900,0.11450,0.3135,0.10550
360,12.540,18.07,79.42,491.9,0.07436,0.02650,0.001194,0.005449,0.1528,0.05185,...,13.720,20.98,86.82,585.7,0.09293,0.04327,0.003581,0.01635,0.2233,0.05521
19,13.540,14.36,87.46,566.3,0.09779,0.08129,0.066640,0.047810,0.1885,0.05766,...,15.110,19.26,99.70,711.2,0.14400,0.17730,0.239000,0.12880,0.2977,0.07259
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,12.200,15.21,78.01,457.9,0.08673,0.06545,0.019940,0.016920,0.1638,0.06129,...,13.750,21.38,91.11,583.1,0.12560,0.19280,0.116700,0.05556,0.2661,0.07961
407,12.850,21.37,82.63,514.5,0.07551,0.08316,0.061260,0.018670,0.1580,0.06114,...,14.400,27.01,91.63,645.8,0.09402,0.19360,0.183800,0.05601,0.2488,0.08151
22,15.340,14.26,102.50,704.4,0.10730,0.21350,0.207700,0.097560,0.2521,0.07032,...,18.070,19.08,125.10,980.9,0.13900,0.59540,0.630500,0.23930,0.4667,0.09946
510,11.740,14.69,76.31,426.0,0.08099,0.09661,0.067260,0.026390,0.1499,0.06758,...,12.450,17.60,81.25,473.8,0.10730,0.27930,0.269000,0.10560,0.2604,0.09879


Scaling

In [212]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [213]:
x_train_scaled

array([[-0.81367471, -0.86157464, -0.76833667, ..., -0.48701142,
        -1.17698435,  1.11931268],
       [ 0.34333604,  0.77876559,  0.33050277, ...,  0.48738104,
        -0.54281162, -0.87753359],
       [-1.16359991,  0.44437116, -1.18583011, ..., -1.34200777,
        -0.87181852, -0.19399348],
       ...,
       [-0.1392221 , -0.04140453, -0.10952466, ...,  0.38375422,
        -0.24400341,  0.23730757],
       [ 1.41568747,  1.23968764,  1.64976563, ...,  0.92441589,
         0.4426197 ,  1.00843837],
       [-1.02814499,  0.19809419, -0.96253872, ..., -0.80780401,
        -0.81777874,  0.34097504]], shape=(455, 30))

In [214]:
x_test_scaled

array([[ 2.57834217,  1.66219952,  2.73549438, ...,  2.37519135,
         0.47758661,  0.19462096],
       [-1.80418879,  1.18094267, -1.81145569, ..., -1.72933178,
        -0.04214893, -0.76056119],
       [-1.44241128, -0.09337123, -1.3136593 , ..., -0.00972732,
         0.37745408,  1.18583726],
       ...,
       [ 0.33487011, -1.14174295,  0.42473583, ...,  1.86456645,
         2.81242306,  0.85099686],
       [-0.68104177, -1.04458781, -0.64829195, ..., -0.1433909 ,
        -0.46652016,  0.81385396],
       [ 1.80512035,  0.34947545,  1.87100847, ...,  1.49661615,
         0.28526857, -0.46674428]], shape=(114, 30))

In [215]:
y_train

388    B
91     M
425    B
205    M
371    B
      ..
183    B
427    B
423    B
12     M
113    B
Name: diagnosis, Length: 455, dtype: object

In [216]:
y_test

202    M
568    B
318    B
360    B
19     B
      ..
324    B
407    B
22     M
510    B
535    M
Name: diagnosis, Length: 114, dtype: object

Encoding

In [217]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

In [218]:
y_train_encoded

array([0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,

In [219]:
y_test_encoded

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1])

In [220]:
x_train_scaled
x_test_scaled
y_train_encoded
y_test_encoded
print("")

In [221]:
x_train_tensor = torch.from_numpy(x_train_scaled)
x_test_tensor = torch.from_numpy(x_test_scaled)
y_train_tensor = torch.from_numpy(y_train_encoded).to(torch.float64)
y_test_tensor = torch.from_numpy(y_test_encoded).to(torch.float64)

In [222]:
x_train_tensor.shape[1]

30

In [223]:
y_train.shape

(455,)

This means that there will be 30 input going to the network and 1 output comming out of there (M or B)

In [224]:
# at the rate which the model steps move
learning_rate = 0.1
# number of times we send the whole dataset to the ANN
epochs = 50

In [225]:
# defining the model

class ANN():
    def __init__(self, X):
        self.weight = torch.rand((X.shape[1], 1), dtype= torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype= torch.float64, requires_grad= True)
    
    def forward_pass(self, X):
        z = X @ self.weight + self.bias
        self.y_pred = torch.sigmoid(z).reshape(X.shape[0])
        return self.y_pred
    
    def loss_function(self, y_real):
        loss_fn = torch.nn.BCELoss()
        self.loss = loss_fn(self.y_pred, y_real)
        return self.loss.item()
    
    def backward_propagation(self, learning_rate):
        self.loss.backward()
        gradient = self.weight.grad
        with torch.no_grad():
            self.weight -=learning_rate * gradient
        self.weight.grad.zero_()
        return self.weight

In [226]:
model = ANN(x_train_tensor)

1. Forward Propagation
2. Loss Calculation
3. Backward Propagtation
4. Adjustment

In [227]:
import time
for epoch in range(epochs):
    y_prep = model.forward_pass(x_train_tensor)
    loss = model.loss_function(y_train_tensor)
    print("epoch: ", epoch, "====> loss", loss)
    new_weight = model.backward_propagation(learning_rate)
    # time.sleep(1)

epoch:  0 ====> loss 0.3906068957144878
epoch:  1 ====> loss 0.37973229482192217
epoch:  2 ====> loss 0.3691289471224244
epoch:  3 ====> loss 0.35879747078711105
epoch:  4 ====> loss 0.3487378034433582
epoch:  5 ====> loss 0.3389486186653612
epoch:  6 ====> loss 0.3294269338517121
epoch:  7 ====> loss 0.3201680117789515
epoch:  8 ====> loss 0.3111655842489849
epoch:  9 ====> loss 0.3024123402141256
epoch:  10 ====> loss 0.2939005598412545
epoch:  11 ====> loss 0.2856227609150991
epoch:  12 ====> loss 0.27757224972386446
epoch:  13 ====> loss 0.26974351374669553
epoch:  14 ====> loss 0.26213243664374014
epoch:  15 ====> loss 0.2547363457373651
epoch:  16 ====> loss 0.24755391723165235
epoch:  17 ====> loss 0.24058496943125596
epoch:  18 ====> loss 0.2338301747045086
epoch:  19 ====> loss 0.22729072069242626
epoch:  20 ====> loss 0.2209679516742386
epoch:  21 ====> loss 0.21486302148719869
epoch:  22 ====> loss 0.20897658841912656
epoch:  23 ====> loss 0.2033085785754592
epoch:  24 ====>

In [228]:
# testing the ANN
y_pred = model.forward_pass(x_test_tensor)
loss = model.loss_function(y_test_tensor)
print(loss)

0.09032950207660619


In [229]:
y_pred

tensor([1.0000e+00, 1.3322e-05, 1.2776e-01, 3.3122e-05, 2.0704e-02, 2.1722e-01,
        2.9465e-01, 1.4818e-03, 1.0000e+00, 2.7270e-02, 1.0000e+00, 9.9864e-01,
        9.9996e-01, 3.0078e-03, 2.4670e-01, 9.4200e-02, 3.8268e-03, 7.4162e-04,
        9.9999e-01, 7.0964e-03, 9.9999e-01, 2.9814e-04, 7.2698e-05, 8.7034e-01,
        6.3589e-01, 2.2797e-03, 5.6753e-04, 9.9361e-01, 9.0993e-05, 9.9268e-01,
        9.9981e-01, 1.0000e+00, 2.4753e-02, 3.7469e-04, 9.9999e-01, 1.2582e-02,
        5.8576e-01, 4.4455e-03, 1.0000e+00, 9.0667e-01, 2.0870e-03, 1.1200e-02,
        9.4277e-01, 9.0763e-04, 2.5098e-01, 5.0870e-04, 9.9999e-01, 2.0361e-01,
        8.5438e-01, 6.3289e-05, 1.0262e-02, 6.1831e-04, 1.4711e-03, 3.7522e-03,
        1.0711e-03, 9.2804e-03, 9.9486e-01, 9.1224e-02, 9.4084e-04, 1.5742e-03,
        9.9985e-01, 5.4375e-04, 5.4210e-04, 5.4457e-05, 1.4825e-02, 8.2450e-03,
        9.9964e-01, 1.4869e-04, 9.9497e-01, 6.8333e-01, 5.4709e-01, 1.3982e-02,
        9.9408e-01, 6.4580e-03, 1.3610e-

In [230]:
y_test_tensor

tensor([1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
        0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
        1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
        1., 0., 0., 1., 0., 1.], dtype=torch.float64)