In [19]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from sklearn.model_selection import train_test_split

In [20]:
full_df = pd.read_csv("fashion-mnist_test.csv")
full_df

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,9,8,...,103,87,56,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,14,53,99,...,0,0,0,0,63,53,31,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,137,126,140,0,133,224,222,56,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,32,23,14,20,0,0,1,0,0,0
9996,6,0,0,0,0,0,0,0,0,0,...,0,0,0,2,52,23,28,0,0,0
9997,8,0,0,0,0,0,0,0,0,0,...,175,172,172,182,199,222,42,0,1,0
9998,8,0,1,3,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0


In [21]:
df = full_df[0:6000]
df.shape

(6000, 785)

In [22]:
features = df.iloc[:, 1:]
features

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,9,8,0,...,103,87,56,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,14,53,99,17,...,0,0,0,0,63,53,31,0,0,0
3,0,0,0,0,0,0,0,0,0,161,...,137,126,140,0,133,224,222,56,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5996,0,0,0,0,0,2,37,18,68,162,...,35,29,16,12,0,0,0,0,0,0
5997,0,0,0,0,0,0,0,0,0,0,...,115,81,67,24,0,0,0,0,0,0
5998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [23]:
labels = df.iloc[:,0]

In [24]:
x_train, x_test, y_train, y_test = train_test_split(features, labels, test_size= 0.2, random_state=42, shuffle= True)

In [25]:
x_train = x_train/255.0

In [41]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = torch.tensor(features.to_numpy()).to(torch.float32)
        self.labels = torch.tensor(labels.to_numpy()).to(torch.long)
    
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]


In [42]:
train_dataset = CustomDataset(x_train, y_train)

In [351]:
test_dataset = CustomDataset(x_test, y_test)

In [43]:
train_dataset.__len__()

4800

In [44]:
train_dataset.__getitem__(4)

(tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0

In [345]:
class ImageClassificationModel(nn.Module):

    def __init__(self, number_features):        
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(number_features, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32,10)
        )
        
        # optimization/ gradient descent
        self.optim = torch.optim.SGD(self.model.parameters(), lr=0.01)
    
    def forward(self, features):
        self.y_pred = self.model(features)
        return self.y_pred
    
    def loss_function(self, labels):
        loss_fn = nn.CrossEntropyLoss()
        self.loss = loss_fn(self.y_pred, labels)
        return self.loss.item()

    def optimization(self):
        self.optim.zero_grad()
        self.loss.backward()
        self.optim.step()


In [346]:
train_dataset.__len__()

4800

In [347]:
x_train.shape

(4800, 784)

In [348]:
model = ImageClassificationModel(x_train.shape[1])

In [349]:
dataloader = DataLoader(train_dataset, batch_size=25, shuffle= True)

In [350]:
# mini-batch gradient descent
# perfor optimization on each mini batch
batch = 0
for features_batch, target_batch in dataloader:
    batch +=1 
    y_pred = model(features_batch)
    print(target_batch)
    loss = model.loss_function(target_batch)
    print(batch)
    print(loss)
    model.optimization()    

tensor([5, 4, 3, 9, 3, 1, 1, 7, 1, 1, 3, 0, 7, 6, 8, 4, 2, 2, 7, 2, 2, 3, 2, 0,
        1])
1
2.299252510070801
tensor([1, 7, 6, 6, 3, 9, 7, 1, 9, 2, 9, 2, 4, 9, 1, 2, 9, 7, 4, 1, 9, 2, 7, 1,
        9])
2
2.28922176361084
tensor([3, 4, 5, 3, 9, 3, 1, 6, 4, 9, 2, 3, 8, 9, 3, 9, 0, 9, 7, 7, 1, 5, 7, 8,
        9])
3
2.332580804824829
tensor([4, 1, 8, 0, 3, 8, 3, 0, 5, 8, 2, 8, 9, 2, 6, 8, 9, 5, 4, 8, 2, 1, 8, 1,
        6])
4
2.3298027515411377
tensor([5, 1, 8, 0, 9, 5, 7, 9, 5, 6, 8, 7, 3, 9, 9, 4, 9, 1, 2, 2, 2, 9, 9, 6,
        6])
5
2.3118090629577637
tensor([0, 9, 3, 5, 5, 5, 0, 6, 0, 9, 9, 9, 0, 6, 2, 0, 6, 4, 9, 7, 1, 0, 5, 4,
        6])
6
2.33280873298645
tensor([0, 6, 0, 8, 5, 1, 8, 1, 5, 4, 8, 7, 1, 5, 4, 8, 3, 6, 3, 2, 1, 2, 9, 4,
        6])
7
2.310213565826416
tensor([8, 6, 0, 5, 6, 4, 6, 5, 6, 9, 5, 2, 9, 6, 5, 0, 0, 0, 5, 5, 2, 1, 0, 3,
        8])
8
2.3208184242248535
tensor([7, 2, 0, 0, 8, 9, 3, 8, 3, 1, 9, 6, 2, 3, 1, 0, 3, 5, 5, 0, 8, 3, 1, 6,
        4])
9
2.3429214