Use the torch.nn module to make the deep learning model easily

In [1]:
import torch
# nn module
import torch.nn as nn
import pandas as pd

In [2]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        # the only task of the nn.Lienar is to define a layer of m number of neurons that takes input from n nuerons
        # from previous layers, and perfomrm the linear combination wti the help of the orresponding weight
        self.layer = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        self.optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.001)
    
    def forward(self, features):
        out = self.layer(features)
        self.y_pred = self.sigmoid(out).to(torch.float64)
        return self.layer.parameters()
    
    def loss_function(self, real_class):
        loss_fn = nn.BCELoss()
        self.loss = loss_fn(self.y_pred, real_class)
        return self.loss.item()
    
    def optimization(self):
        self.optimizer.zero_grad()
        self.loss.backward()
        self.optimizer.step()
        return {'weights': self.layer.weight, 'bais' : self.layer.bias}
        

In [3]:
features = torch.rand(10,5)
print(features)
target = torch.randint(low=0, high= 2, size=(10,1), dtype=torch.float64)
print(target)

tensor([[0.7200, 0.4857, 0.6415, 0.7776, 0.8801],
        [0.0721, 0.0373, 0.8646, 0.3291, 0.4786],
        [0.5694, 0.5012, 0.7287, 0.9654, 0.0470],
        [0.3355, 0.7210, 0.9631, 0.9539, 0.0222],
        [0.6530, 0.6982, 0.4177, 0.3109, 0.6910],
        [0.1595, 0.1410, 0.0378, 0.5268, 0.3940],
        [0.1595, 0.1886, 0.9360, 0.0909, 0.6259],
        [0.2806, 0.1513, 0.9000, 0.8384, 0.9230],
        [0.0975, 0.2976, 0.5177, 0.5388, 0.0330],
        [0.0914, 0.2022, 0.2720, 0.2190, 0.4281]])
tensor([[1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.]], dtype=torch.float64)


In [14]:
ann = Model(features.shape[1])


In [15]:
y_pred = ann(features)
y_pred

<generator object Module.parameters at 0x000001A25972FD80>

In [16]:
ann.layer.weight

Parameter containing:
tensor([[ 0.1259, -0.2983,  0.1960,  0.2402, -0.1046]], requires_grad=True)

In [17]:
ann.layer.bias

Parameter containing:
tensor([0.2059], requires_grad=True)

In [18]:
loss = 1
for epoch in range(20):
    ann(features)
    loss = ann.loss_function(target)
    print("epoch: ", epoch, "===============>  loss:", loss)
    ann.optimization()

print('weight: ', ann.layer.weight)
print('bias: ', ann.layer.bias)

epoch:  0 ===============>  loss: 0.7612891749735956
epoch:  1 ===============>  loss: 0.7612096988451136
epoch:  2 ===============>  loss: 0.761130274140922
epoch:  3 ===============>  loss: 0.7610508909575071
epoch:  4 ===============>  loss: 0.760971638706244
epoch:  5 ===============>  loss: 0.7608924465228892
epoch:  6 ===============>  loss: 0.7608132964075766
epoch:  7 ===============>  loss: 0.7607342032658395
epoch:  8 ===============>  loss: 0.7606551820010925
epoch:  9 ===============>  loss: 0.7605762950847066
epoch:  10 ===============>  loss: 0.7604974105553638
epoch:  11 ===============>  loss: 0.7604186218610256
epoch:  12 ===============>  loss: 0.7603398656075897
epoch:  13 ===============>  loss: 0.7602611719712176
epoch:  14 ===============>  loss: 0.7601825824677333
epoch:  15 ===============>  loss: 0.7601040535345474
epoch:  16 ===============>  loss: 0.7600255995653284
epoch:  17 ===============>  loss: 0.7599471900204533
epoch:  18 ===============>  loss: 0.759

In [9]:
# ann.layer.parameters() ---> they are the generator so use iteration
for i in ann.layer.parameters():
    print(i)

Parameter containing:
tensor([[-0.1229, -0.3618, -0.0382, -0.0280, -0.4019]], requires_grad=True)
Parameter containing:
tensor([0.1705], requires_grad=True)


In [ ]:
# making a multi-layer ANN with the overfitting control method dropout and fast convergene method BatchNormalization
