Use the torch.nn module to make the deep learning model easily

In [2]:
import torch
# nn module
import torch.nn as nn
import pandas as pd

In [203]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        # the only task of the nn.Lienar is to define a layer of m number of neurons that takes input from n nuerons
        # from previous layers, and perfomrm the linear combination wti the help of the orresponding weight
        self.layer = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.layer(features)
        self.y_pred = self.sigmoid(out).to(torch.float64)
        return self.y_pred
    
    def loss_function(self, real_class):
        loss_fn = nn.BCELoss()
        self.loss = loss_fn(self.y_pred, real_class)
        return self.loss.item()
    
    def optimization(self, learning_rate = 0.01):
        self.loss.backward()
        self.optimizer = torch.optim.SGD(self.layer.parameters(), lr=learning_rate)
        self.optimizer.step()
        return {'weights': self.layer.weight, 'bais' : self.layer.bias}
        

In [204]:
features = torch.rand(10,5)
print(features)
target = torch.randint(low=0, high= 2, size=(10,1), dtype=torch.float64)
print(target)

tensor([[0.6984, 0.1857, 0.3139, 0.0252, 0.9439],
        [0.7785, 0.6133, 0.7304, 0.9562, 0.4624],
        [0.7437, 0.6608, 0.2237, 0.3318, 0.3166],
        [0.4268, 0.5745, 0.9213, 0.7553, 0.0018],
        [0.1662, 0.3012, 0.2477, 0.0325, 0.1669],
        [0.0841, 0.4591, 0.7507, 0.3522, 0.4552],
        [0.4044, 0.0639, 0.6825, 0.6770, 0.5294],
        [0.1624, 0.0476, 0.3595, 0.5779, 0.5489],
        [0.5835, 0.6587, 0.8944, 0.0193, 0.7374],
        [0.1273, 0.9262, 0.3871, 0.5953, 0.6363]])
tensor([[0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.]], dtype=torch.float64)


In [213]:
ann = Model(features.shape[1])


In [221]:
y_pred = ann(features)

In [222]:
ann.layer.weight

Parameter containing:
tensor([[-0.3965,  1.0076,  0.3855, -0.5338,  0.2441]], requires_grad=True)

In [223]:
ann.layer.bias

Parameter containing:
tensor([-0.2217], requires_grad=True)

In [224]:
for epoch in range(20):
    ann(features)
    ann.loss_function(target)
    ann.optimization()
print('weight: ', ann.layer.weight)
print('bias: ', ann.layer.bias)

weight:  Parameter containing:
tensor([[-0.7363,  1.4128,  0.3646, -0.9086,  0.4578]], requires_grad=True)
bias:  Parameter containing:
tensor([-0.6108], requires_grad=True)
