In [2]:
import numpy as np
import torch

# Tensors in python:
### Tensors are the multi dimenstional matrix 

In [5]:
scalar_tensor = torch.tensor(18)

In [8]:
print(scalar_tensor)

tensor(18)


In [11]:
vector_tensor = torch.tensor([1,2,3])
vector_tensor

tensor([1, 2, 3])

In [14]:
matrix_tensor = torch.tensor([[1,2,3], [4,5,6]])
matrix_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
tensor = torch.tensor([[[1,2,3]], [[4,5,6]]])
tensor

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [25]:
tensor.shape

torch.Size([2, 1, 3])

In [28]:
tensor.T.shape


torch.Size([3, 1, 2])

In [30]:
tensor.T

tensor([[[1, 4]],

        [[2, 5]],

        [[3, 6]]])

In [32]:
matrix_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [36]:
matrix_tensor @ matrix_tensor.T

tensor([[14, 32],
        [32, 77]])

In [38]:
matrix_tensor.device

device(type='cpu')