In [2]:
import numpy as np
import torch

# Tensors in python:
### Tensors are the multi dimenstional matrix 

In [5]:
scalar_tensor = torch.tensor(18)

In [8]:
print(scalar_tensor)

tensor(18)


In [11]:
vector_tensor = torch.tensor([1,2,3])
vector_tensor

tensor([1, 2, 3])

In [14]:
matrix_tensor = torch.tensor([[1,2,3], [4,5,6]])
matrix_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
tensor = torch.tensor([[[1,2,3], [1,2,3]], [[4,5,6], [4,5,6]]])
tensor

tensor([[[1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6]]])