In [1]:
import numpy as np
import torch
import math

# Tensors in python:
### Tensors are the multi dimenstional matrix 

In [2]:
scalar_tensor = torch.tensor(18)

In [3]:
print(scalar_tensor)

tensor(18)


In [4]:
vector_tensor = torch.tensor([1,2,3])
vector_tensor

tensor([1, 2, 3])

In [5]:
matrix_tensor = torch.tensor([[1,2,3], [4,5,6]])
matrix_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
tensor = torch.tensor([[[1,2,3]], [[4,5,6]]])
tensor

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [7]:
tensor.shape

torch.Size([2, 1, 3])

In [8]:
tensor.T.shape


C:\Users\Nitro\AppData\Local\Temp\ipykernel_5744\256523501.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4483.)
  tensor.T.shape


torch.Size([3, 1, 2])

In [9]:
tensor.T

tensor([[[1, 4]],

        [[2, 5]],

        [[3, 6]]])

In [10]:
matrix_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
matrix_tensor @ matrix_tensor.T

tensor([[14, 32],
        [32, 77]])

In [12]:
matrix_tensor.device

device(type='cpu')

In [13]:
import torch.nn as nn

In [14]:
torch.zeros(5,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [29]:
torch.ones(10,10)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
torch.rand(5,5)

tensor([[0.7064, 0.1629, 0.8902, 0.5163, 0.0359],
        [0.6476, 0.3430, 0.3182, 0.5261, 0.0447],
        [0.5123, 0.9051, 0.5989, 0.4450, 0.7278],
        [0.4563, 0.3389, 0.6211, 0.5530, 0.6896],
        [0.3687, 0.9053, 0.8356, 0.3039, 0.6726]])

In [31]:
torch.manual_seed(100)
torch.rand(5,5)

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765],
        [0.7539, 0.2627, 0.0428, 0.2080, 0.1180],
        [0.1217, 0.7356, 0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565, 0.2239, 0.3023],
        [0.1784, 0.8238, 0.5557, 0.9770, 0.4440]])

In [32]:
torch.manual_seed(100)
torch.rand(5,5)

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765],
        [0.7539, 0.2627, 0.0428, 0.2080, 0.1180],
        [0.1217, 0.7356, 0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565, 0.2239, 0.3023],
        [0.1784, 0.8238, 0.5557, 0.9770, 0.4440]])

In [33]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [34]:
for i in torch.randn(2,3):
    for j in i:
        print(j)
    print("="*50,"next row", "="*50)

tensor(-1.9206)
tensor(-1.0997)
tensor(-2.2002)
================================================== next row ==================================================
tensor(-1.6568)
tensor(-1.3010)
tensor(1.1056)
================================================== next row ==================================================


In [35]:
tensor

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [36]:
torch.linspace(0, 10, 10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

## Tensors shape

In [23]:
tensor

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [24]:
tensor.shape

torch.Size([2, 1, 3])

In [25]:
a = tensor.reshape(2,3,1)
a

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

In [26]:
torch.empty_like(a)

tensor([[[0],
         [0],
         [0]],

        [[0],
         [0],
         [0]]])

In [27]:
torch.zeros_like(a)

tensor([[[0],
         [0],
         [0]],

        [[0],
         [0],
         [0]]])

In [28]:
torch.ones_like(a)

tensor([[[1],
         [1],
         [1]],

        [[1],
         [1],
         [1]]])

## Tensor data-type

In [29]:
a.dtype

torch.int64

In [37]:
b = torch.tensor(a, dtype= torch.float64)

C:\Users\Nitro\AppData\Local\Temp\ipykernel_5744\3875274079.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  b = torch.tensor(a, dtype= torch.float64)


In [38]:
torch.rand_like(b)

tensor([[[0.6512],
         [0.1216],
         [0.2871]],

        [[0.7442],
         [0.2087],
         [0.0988]]], dtype=torch.float64)

In [39]:
c = a.to(torch.float64)
c

tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]], dtype=torch.float64)

In [41]:
k = torch.randint(low=0, high= 10, size=(2,3))
l = k.clone()
k


tensor([[7, 8, 3],
        [6, 1, 5]])

In [42]:
torch.sigmoid(k)

tensor([[0.9991, 0.9997, 0.9526],
        [0.9975, 0.7311, 0.9933]])

In [43]:
torch.log(k)

tensor([[1.9459, 2.0794, 1.0986],
        [1.7918, 0.0000, 1.6094]])

In [44]:
torch.sqrt(k)

tensor([[2.6458, 2.8284, 1.7321],
        [2.4495, 1.0000, 2.2361]])

In [45]:
torch.square(k)

tensor([[49, 64,  9],
        [36,  1, 25]])

In [79]:
l = l.to(torch.float32)
op = torch.softmax(l, dim=1)
op

tensor([[0.2676, 0.7275, 0.0049],
        [0.7275, 0.0049, 0.2676]])

In [47]:
for i in op:
    a = i[0] + i[1] + i[2]
print(a)

tensor(1.)


In [48]:
torch.tanh(k)

tensor([[1.0000, 1.0000, 0.9951],
        [1.0000, 0.7616, 0.9999]])

In [49]:
torch.relu(k)

tensor([[7, 8, 3],
        [6, 1, 5]])

In [50]:
m = l.clone()
m

tensor([[7., 8., 3.],
        [6., 1., 5.]])

In [51]:
m.log_()

tensor([[1.9459, 2.0794, 1.0986],
        [1.7918, 0.0000, 1.6094]])

In [52]:
# same tensor got updated instead of the new array formed
m

tensor([[1.9459, 2.0794, 1.0986],
        [1.7918, 0.0000, 1.6094]])

In [53]:
l

tensor([[7., 8., 3.],
        [6., 1., 5.]])

In [54]:
id(k)

1640551545696

In [55]:
id(l)

1640551790496

In [56]:
id(m)

1640403170112

In [57]:
torch.cuda.is_available()

False

In [58]:
device = torch.device('cuda')

In [59]:
device

device(type='cuda')

In [60]:
print(torch.version.cuda)

None


In [61]:
import torch

print("Torch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)

Torch version: 2.11.0+cpu
CUDA available: False
CUDA version: None


In [62]:
# training a deep neural network

In [63]:
# one neuron input layer and one neuron output layer (regression)
# one neuron hidden layer (sigmoid)
# forward propagation
# loss function
# backpropagation -> gradient(dL/dW and dL/db) that is the loss due to the wieght and bias w and b, 
# gradient descent is adjusting the wieght towards the opitmal value where the loss due to the weight become nearly 0 (still loss but not because of the wieght)

In [64]:
# forward propagtion 
# ==> z = x*w + b
# ==> y = sig(z)
# ==> loss = (y - y(real)^2) (SSR)

In [65]:
# backward propagation:- 
##### ==> we need to calculate the gradient or slope dL/dw, 
##### that is the rate with which the loss falls or rises when the weight is increased or decresed.
##### The slope also gives the contribution of weight in bringing the loss L, not all but certain percentage is brought
##### which we try to reduce it.
##### we reduce the dl/dw to nearly 0 which means there is almost no contrubution of w to the loss(L) that is the w is in optimal solution
##### It is done using the gradient descent, but we increase it slowly. The far we are from the minima point then more the slope and
##### the bigger the step and as we move closer to the point of no loss due to the weight then we take less step to avoid overshooting
##### using chain rule to find the relation between the loss and w

In [66]:
# the gradient formula will be:
# dL/dw = dL/dy(predicted) * dy(predicted)/dz * dz(sigmoid)/dw

In [67]:
# performing the differentiation using the AutoGrad

derivative of y = $x^2$

dy/dx = 2x

In [80]:
x = torch.tensor(3.0, requires_grad=True)
z = torch.tensor(3.0, requires_grad=True)

# "requires_grad" makes the pyTorch make the computational graph to remember and
# track the operation it will be used in the future so that we can make the gradient w.r.to this    

In [81]:
y = x ** 2 + z

In [82]:
x

tensor(3., requires_grad=True)

In [83]:
y

tensor(12., grad_fn=<AddBackward0>)

In [84]:
c = y * 2

In [85]:
c.backward()
# this says to start the backpropagration to find the graident from the end to the start, i.e. the tensor

In [86]:
x.grad

tensor(12.)

In [87]:
z.grad

tensor(2.)

In [88]:
s = torch.sin(y)

In [89]:
s

tensor(-0.5366, grad_fn=<SinBackward0>)