In [6]:
import numpy as np
import torch
import math

# Tensors in python:
### Tensors are the multi dimenstional matrix 

In [7]:
scalar_tensor = torch.tensor(18)

In [8]:
print(scalar_tensor)

tensor(18)


In [9]:
vector_tensor = torch.tensor([1,2,3])
vector_tensor

tensor([1, 2, 3])

In [10]:
matrix_tensor = torch.tensor([[1,2,3], [4,5,6]])
matrix_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
tensor = torch.tensor([[[1,2,3]], [[4,5,6]]])
tensor

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [12]:
tensor.shape

torch.Size([2, 1, 3])

In [13]:
tensor.T.shape


C:\Users\Nitro\AppData\Local\Temp\ipykernel_57204\256523501.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4483.)
  tensor.T.shape


torch.Size([3, 1, 2])

In [14]:
tensor.T

tensor([[[1, 4]],

        [[2, 5]],

        [[3, 6]]])

In [15]:
matrix_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
matrix_tensor @ matrix_tensor.T

tensor([[14, 32],
        [32, 77]])

In [17]:
matrix_tensor.device

device(type='cpu')

In [18]:
import torch.nn as nn

In [19]:
torch.zeros(5,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [20]:
torch.ones(10,10)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
torch.rand(5,5)

tensor([[0.2137, 0.7311, 0.3800, 0.2550, 0.8283],
        [0.9560, 0.8302, 0.0902, 0.4954, 0.4475],
        [0.3426, 0.9642, 0.3777, 0.3658, 0.8221],
        [0.7100, 0.3904, 0.0962, 0.7564, 0.3151],
        [0.8226, 0.5635, 0.1990, 0.1376, 0.8289]])

In [22]:
torch.manual_seed(100)
torch.rand(5,5)

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765],
        [0.7539, 0.2627, 0.0428, 0.2080, 0.1180],
        [0.1217, 0.7356, 0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565, 0.2239, 0.3023],
        [0.1784, 0.8238, 0.5557, 0.9770, 0.4440]])

In [23]:
torch.manual_seed(100)
torch.rand(5,5)

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765],
        [0.7539, 0.2627, 0.0428, 0.2080, 0.1180],
        [0.1217, 0.7356, 0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565, 0.2239, 0.3023],
        [0.1784, 0.8238, 0.5557, 0.9770, 0.4440]])

In [24]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [25]:
for i in torch.randn(2,3):
    for j in i:
        print(j)
    print("="*50,"next row", "="*50)

tensor(-1.9206)
tensor(-1.0997)
tensor(-2.2002)
================================================== next row ==================================================
tensor(-1.6568)
tensor(-1.3010)
tensor(1.1056)
================================================== next row ==================================================


In [26]:
tensor

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [27]:
torch.linspace(0, 10, 10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

## Tensors shape

In [28]:
tensor

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [29]:
tensor.shape

torch.Size([2, 1, 3])

In [30]:
a = tensor.reshape(2,3,1)
a

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

In [31]:
torch.empty_like(a)

tensor([[[0],
         [0],
         [0]],

        [[0],
         [0],
         [0]]])

In [32]:
torch.zeros_like(a)

tensor([[[0],
         [0],
         [0]],

        [[0],
         [0],
         [0]]])

In [33]:
torch.ones_like(a)

tensor([[[1],
         [1],
         [1]],

        [[1],
         [1],
         [1]]])

## Tensor data-type

In [34]:
a.dtype

torch.int64

In [35]:
b = torch.tensor(a, dtype= torch.float64)

C:\Users\Nitro\AppData\Local\Temp\ipykernel_57204\3875274079.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  b = torch.tensor(a, dtype= torch.float64)


In [36]:
torch.rand_like(b)

tensor([[[0.6512],
         [0.1216],
         [0.2871]],

        [[0.7442],
         [0.2087],
         [0.0988]]], dtype=torch.float64)

In [37]:
c = a.to(torch.float64)
c

tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]], dtype=torch.float64)

In [38]:
k = torch.randint(low=0, high= 10, size=(2,3))
l = k.clone()
k


tensor([[9, 7, 9],
        [2, 6, 7]])

In [39]:
torch.sigmoid(k)

tensor([[0.9999, 0.9991, 0.9999],
        [0.8808, 0.9975, 0.9991]])

In [40]:
torch.log(k)

tensor([[2.1972, 1.9459, 2.1972],
        [0.6931, 1.7918, 1.9459]])

In [41]:
torch.sqrt(k)

tensor([[3.0000, 2.6458, 3.0000],
        [1.4142, 2.4495, 2.6458]])

In [42]:
torch.square(k)

tensor([[81, 49, 81],
        [ 4, 36, 49]])

In [43]:
l = l.to(torch.float32)
op = torch.softmax(l, dim=1)
op

tensor([[0.4683, 0.0634, 0.4683],
        [0.0049, 0.2676, 0.7275]])

In [44]:
for i in op:
    a = i[0] + i[1] + i[2]
print(a)

tensor(1.)


In [45]:
torch.tanh(k)

tensor([[1.0000, 1.0000, 1.0000],
        [0.9640, 1.0000, 1.0000]])

In [46]:
torch.relu(k)

tensor([[9, 7, 9],
        [2, 6, 7]])

In [47]:
m = l.clone()
m

tensor([[9., 7., 9.],
        [2., 6., 7.]])

In [48]:
m.log_()

tensor([[2.1972, 1.9459, 2.1972],
        [0.6931, 1.7918, 1.9459]])

In [49]:
# same tensor got updated instead of the new array formed
m

tensor([[2.1972, 1.9459, 2.1972],
        [0.6931, 1.7918, 1.9459]])

In [50]:
l

tensor([[9., 7., 9.],
        [2., 6., 7.]])

In [51]:
id(k)

1970651884720

In [52]:
id(l)

1970651883520

In [53]:
id(m)

1970651947376

In [54]:
torch.cuda.is_available()

False

In [55]:
device = torch.device('cuda')

In [56]:
device

device(type='cuda')

In [57]:
print(torch.version.cuda)

None


In [58]:
import torch

print("Torch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)

Torch version: 2.11.0+cpu
CUDA available: False
CUDA version: None


In [59]:
# training a deep neural network

In [60]:
# one neuron input layer and one neuron output layer (regression)
# one neuron hidden layer (sigmoid)
# forward propagation
# loss function
# backpropagation -> gradient(dL/dW and dL/db) that is the loss due to the wieght and bias w and b, 
# gradient descent is adjusting the wieght towards the opitmal value where the loss due to the weight become nearly 0 (still loss but not because of the wieght)

In [61]:
# forward propagtion 
# ==> z = x*w + b
# ==> y = sig(z)
# ==> loss = (y - y(real)^2) (SSR)

In [62]:
# backward propagation:- 
##### ==> we need to calculate the gradient or slope dL/dw, 
##### that is the rate with which the loss falls or rises when the weight is increased or decresed.
##### The slope also gives the contribution of weight in bringing the loss L, not all but certain percentage is brought
##### which we try to reduce it.
##### we reduce the dl/dw to nearly 0 which means there is almost no contrubution of w to the loss(L) that is the w is in optimal solution
##### It is done using the gradient descent, but we increase it slowly. The far we are from the minima point then more the slope and
##### the bigger the step and as we move closer to the point of no loss due to the weight then we take less step to avoid overshooting
##### using chain rule to find the relation between the loss and w

In [63]:
# the gradient formula will be:
# dL/dw = dL/dy(predicted) * dy(predicted)/dz * dz(sigmoid)/dw

In [64]:
# performing the differentiation using the AutoGrad

derivative of y = $x^2$

dy/dx = 2x

In [65]:
x = torch.tensor(3.0, requires_grad=True)
z = torch.tensor(3.0, requires_grad=True)

# "requires_grad" makes the pyTorch make the computational graph to remember and
# track the operation it will be used in the future so that we can make the gradient w.r.to this    

if we add the requires_grad property as True for a tensor then PyTorch will:

Track all operations done using that tensor

Build a computational graph

Allow you to compute gradients of some final output with respect to that tensor

In [66]:
y = x ** 2 + z

In [67]:
x

tensor(3., requires_grad=True)

In [68]:
y

tensor(12., grad_fn=<AddBackward0>)

In [69]:
c = y * 2

In [70]:
c.backward()
# this says to start the backpropagration to find the graident from the end to the start, i.e. the tensor

In [71]:
x.grad

tensor(12.)

In [72]:
z.grad

tensor(2.)

In [73]:
x = torch.tensor(2.0, requires_grad= True)

In [74]:
y = x**2

In [75]:
s = torch.sin(x)

In [76]:
s

tensor(0.9093, grad_fn=<SinBackward0>)

In [77]:
s.backward()

In [78]:
x.grad

tensor(-0.4161)

In [79]:
torch.cos(x)

tensor(-0.4161, grad_fn=<CosBackward0>)

In ANN or in any Deep Learning models, 
finding the weight's contribution in loss (dL/dw) and 
finding the bias's contribution in loss (dL/db) can be a lot complex as we have to find the gradient for each of the weights on our own if we dont use the the requires_grad.
And if we do, then all the computational graph will be calculated respect to the tensor and we can calcuate the gradient easily.

In [80]:
x = torch.tensor(6.7)
y_real = torch.tensor(0.0)

weight = torch.tensor(1.0, requires_grad= True)
bias = torch.tensor(0.0, requires_grad= True)

In [81]:
# weight = torch.rand(1)
# # w = weight[0]
# weight = weight[0]
# weight

In [82]:
# lineasr combination for the raw value
z = weight * x + bias
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [83]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [85]:
y_real

tensor(0.)

In [87]:
# Cross entropy as Loss function:

loss_fn = torch.nn.BCELoss()
loss = loss_fn(y_pred, y_real)
L = loss.item()
L

6.701176166534424

In [98]:
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [96]:
y_real

tensor(0.)

In [80]:
# gradients
# since the loss has the relation with the y_pred, we use the loss for backward as it is also the actual loss
loss.backward()
dL_dw = weight.grad
dL_db = bias.grad

In [81]:
dL_dw

tensor(6.6918)

In [82]:
dL_db

tensor(0.9988)

In [83]:
# gradient descent
weight = weight - (dL_dw*0.0001)
bias = bias - (dL_db*0.001)

In [84]:
weight

tensor(0.9993, grad_fn=<SubBackward0>)

In [85]:
bias

tensor(-0.0010, grad_fn=<SubBackward0>)

In [86]:
x = torch.rand((3,), requires_grad= True)
y = (x**2).mean()
y.backward()
x.grad

tensor([0.3687, 0.4597, 0.2458])

In [87]:
x

tensor([0.5530, 0.6896, 0.3687], requires_grad=True)

In [88]:
x = torch.tensor(3.0, requires_grad= True)
x

tensor(3., requires_grad=True)

In [89]:
x

tensor(3., requires_grad=True)

In [90]:
n = x**2
n


tensor(9., grad_fn=<PowBackward0>)

In [91]:
n.backward()

In [92]:
x.grad

tensor(6.)

In [93]:
# again tru nthe gradient to 0
x.grad.zero_()

tensor(0.)

In [94]:
# turn off the gradient tracking system
x.requires_grad_(False)

tensor(3.)